---

# Before we can use eAPI to connect to a switch, we must enable eAPI

ansible_connection: network_cli
ansible_network_os: eos
ansible_user: myuser
ansible_ssh_pass: !vault...
ansible_become: yes
ansible_become_method: enable
ansible_become_pass: !vault...
# if accessing host through a bastion/jump host
# ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q bastion01"'

# Once eAPI is enabled

# ansible_connection: httpapi
# ansible_network_os: eos
# ansible_user: myuser
# ansible_ssh_pass: !vault...
# ansible_become: yes
# ansible_become_method: enable
# proxy_env:
#   http_proxy: http://proxy.example.com:8080

# connection: local

# ansible_connection: local
# ansible_network_os: eos
# ansible_user: myuser
# ansible_ssh_pass: !vault...
# eapi:
#   host: "{{ inventory_hostname }}"
#   transport: eapi
#   authorize: yes
#   auth_pass: !vault...
# proxy_env:
#   http_proxy: http://proxy.example.com:8080
